
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  labels:
    env: pre-prod
spec:
  replicas: 4
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name : myapplication
          image: httpd
          ports:
            - containerPort: 80
